### ISSUE TITLE
9anime api changed

### ISSUE THREAD

**Issue by shizuru84** [vn-ki/anime-downloader#21]
Traceback (most recent call last):
  File "/home/sunny/.local/lib/python3.6/site-packages/anime_downloader/sites/nineanime.py", line 33, in getData
    url = data['target']
KeyError: 'target'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sunny/.local/bin/anime", line 11, in <module>
    sys.exit(cli())
  File "/home/sunny/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sunny/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sunny/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sunny/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sunny/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sunny/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sunny/.local/lib/python3.6/site-packages/anime_downloader/cli.py", line 94, in dl
    for episode in anime:
  File "/home/sunny/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 71, in __getitem__
    ep_no=ep_id[0])
  File "/home/sunny/.local/lib/python3.6/site-packages/anime_downloader/sites/anime.py", line 113, in __init__
    self.getData()
  File "/home/sunny/.local/lib/python3.6/site-packages/anime_downloader/sites/nineanime.py", line 39, in getData
    ) from e
anime_downloader.sites.exceptions.AnimeDLError: 9anime probably changed their API again. Check the issueshere https://github.com/vn-ki/anime-downloader/issues. If it has not been reported yet, please open a new issue

**Comment by vn-ki** [comment]
9anime doesn't work for now. You can still use KissAnime.

Use `--provider kissanime` to use it. If you are providing the KissAnime url, then the tool will automatically use the correct provider.

**Comment by vn-ki** [comment]
The latest release provides a fallback if 9anime is not working. This should cover you, at least for now.
Update using `pip install -U anime-downloader`

**Comment by grabberboy** [comment]
when this going to fixed?

**Comment by vn-ki** [comment]
@grabberboy I can't say an exact date. I tried digging into 9anime website but it seems too hard. Some awesome people at DxCx's 9anime kodi plugin seems to be making some progress. Once their fix is release, I can port it over.

In the meantime, the fallback approach to 9anime.cloud somewhat holds. #24 should strengthen that approach. You can try it out now to see if it works or not.

**Comment by grabberboy** [comment]
keep it up man
Thank you!

**Comment by Ryanb58** [comment]
`data` seems to be equal to `{'error': 'token'}` when looking inside fo the `get_stream_url` method.

**Comment by Ryanb58** [comment]
Non working URL:
```
https://www6.9anime.is/ajax/episode/info?id=p29p1j&server=33&_=1120&ts=1529838000
```

Working URL from the 9anime site:
```
https://www6.9anime.is/ajax/episode/info?ts=1529838000&_=826&id=1y112q&server=33```

**Comment by vn-ki** [comment]
@Ryanb58 9anime has been experiencing issues for the past week. Hopefully this will be fixed soon. In the mean time you can use kissanime provider for more reliability by using the `--provider kissanime` cli argument.

**Comment by vn-ki** [comment]
@Ryanb58 You need `cfscrape` (install with `pip install cfscrape`) and node-js, for scraping kissanime. It is mentioned in the readme.

**Comment by vn-ki** [comment]
@Ryanb58 I have released a new version, with updated 9anime key.

**Comment by nirmankmr** [comment]
Hi,

Updated 9anime key "95ec8bcc" was working but  suddenly stopped in middle of download. Getting connection error. Below is the log::

> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www3487.playercdn
> .net', port=443): Max retries exceeded with url: /187/0/klvZ1EgxQG6kTwgnS58HnA/1
> 530291380/180524/VxW2ZojczTDDuPz.mp4 (Caused by NewConnectionError('<urllib3.con
> nection.VerifiedHTTPSConnection object at 0x000000000499BAC8>: Failed to establi
> sh a new connection: [WinError 10060] A connection attempt failed because the co
> nnected party did not properly respond after a period of time, or established co
> nnection failed because connected host has failed to respond'))

Even --provider kissanime is giving the same error.

**Comment by vn-ki** [comment]
@nirmankmr What were you downloading? Can you share the link? It's possible that the link expired. How long were you downloading?

Did you retry after some time?

**Comment by nirmankmr** [comment]
@vn-ki  I was downloading One Piece anime. Link is "anime dl https://www6.9anime.is/watch/one-piece-dub.34r/ --episodes 294:300". I think downloading went for around 30 mins or so. I did tried multiple times since then. even switching to kissanime url. But, still the same problem.

**Comment by vn-ki** [comment]
Can you watch from the 9anime website?

**Comment by nirmankmr** [comment]
Yes, its streaming in all resolutions.

**Comment by vn-ki** [comment]
Try the url flag.

If it still does not work, the version in master has implemented the ability to download by external downloader (aria2). Try that.

**Comment by vn-ki** [comment]
If it still doesn't work, run these and post the output,
```
anime dl www6.9anime.is/watch/one-piece-dub.34r -e 294 --url -ll DEBUG
```

```
anime dl www6.9anime.is/watch/one-piece-dub.34r -e 294 -ll DEBUG
```

**Comment by nirmankmr** [comment]
Log after running :: 

C:\>anime dl http://www6.9anime.is/watch/one-piece-dub.34r -e 294 --url -ll DEBU
G
INFO root: anime-downloader 2.7.1
DEBUG root: Platform: Windows-7-6.1.7601-SP1
DEBUG root: Python 3.7.0
INFO root: Extracting episode info from page
DEBUG root: data-ts: 1530270000
DEBUG root: EPISODE IDS: length: 572, ids: ['v07k4l', 'q37rr5', 'y6wn3z', '1wz61
p', '5m1ln9', 'xz240v', '8p1oqy', 'j0wxk3', 'l21zm6', '4lwmlx', 'xz24ow', '0v07v
r', 'p1wq19', '4lwk0j', 'j0wx73', 'k09y76', 'm83nz8', 'n0w17j', 'p1w97x', 'm83nz
7', 'v07ko6', 'xz24x3', 'y6wnx1', '1wz65q', '3k9j59', 'm8380z', 'n0w018', 'o0402
8', 'p1w196', 'l2xmz3', 'q37343', '8p2qoo', 'r0305q', '3k0lw6', 'v070k4', 'wzwzl
4', 'xz2zmq', 'y6w6nx', 'zzwzop', '0v0v5k', '1wzw6m', '2jwj7l', '3k9kj2', '4lwlk
k', '5m1ml0', '6n1n29', '7o1o4j', '8p1p6n', '9q1q80', 'j0w0o2', 'k090q9', 'l212v
n', 'm838xz', 'n0w0z8', 'o04018', 'p1w136', '3k9188', 'q37353', 'r0307q', 'l21y5
z', 'v070p4', 'wzwzr4', 'xz2zwq', 'y6w6yx', 'zzwz0p', '0v0vnk', 'xz1qpz', '1wzwp
m', '2jwjrl', '3k9kw2', '4lwlyk', 'r03yvy', '5m1m00', '6n1499', 'k0x7w9', '6n1zo
p', '3k0zr2', '7o19mj', '8p14kn', 'j0w8n2', 'k09jo9', 'l21kpn', 'm83lmz', 'n0wmn
8', 'p1wok6', 'r03qmq', 'xz1qjq', 'y6w01x', '1wz42m', '4lw4rk', 'l2x7rn', '5mwj9
0', '6n14l9', 'j0w8v2', 'j0w8v3', 'n0wm3m', 'p1worq', 'v0qoq4', 'wzw017', 'zzw6l
m', '3k947r', '5m17k9', '9q142m', 'l21k36', 'j027w2', 'o04no5', 'r03qjn', 'xz20j
3', '0v04r5', '3k94pr', '4lw42j', '5m1799', '6n14w0', '9q140m', 'm83lv8', 'p1wop
q', 'v07x9l', 'y6w0vz', 'r0ok3n', '9qjnym', '1wz4qp', '5m17w9', 'zzkv5m', '7o190
1', 'j0w823', 'p1womq', 'wzw0q7', 'j027z3', 'y6w0jz', '1wz47p', 'y6jr8z', 'l2x7y
6', '4lw4wj', '7o1911', '9q141m', 'k09j94', 'm83l38', 'zzw65l', '4lw4xx', '9q14y
q', 'l21knm', 'p1wo4x', 'r03qrp', 'xz20xw', 'zzw68l', '0vmwo5', '3k94v9', '6n14j
z', 'j02763', '9q14mq', 'o04374', 'l21k8m', 'n0wm4j', '1wm6lm', 'r03q4p', 'wzw08
l', '9qjn3q', 'zzw6ql', 'y6jr61', '1wz49q', '4lw4zx', 'm8j787', '7o19zy', 'j0w83
8', 'm83ly7', '1wz9xx', 'o04n3y', '3k0z49', 'r03qyp', 'v07xm6', 'm83y1v', 'y6w09
1', 'xz1q0w', '1wz4yq', 'k0x766', '0vmw79', 'p1m7q9', 'l2x77q', '8p2m5q', '5mwj6
m', 'v0qo37', '4lw49x', 'p1m7vj', 'k0x7nv', '9qjnvx', '6n0k57', '1w7x6x', 'p1m73
4', 'o0lk94', '7o19yy', '9q147q', 'k0xzww', 'l21k4m', '6n07lp', 'j0w86y', 'l21k4
q', 'o04n8z', 'q37p25', 'v07xjv', 'xz19jq', 'q3zmn3', 'l2x0xn', '6n0719', 'y6jxw
x', 'l2x0n6', '9qj5mm', 'q3zm8j', 'm8j148', 'k0xz16', 'y6jx01', 'wzqv0l', 'wzqv3
l', 'm8j1np', 'l2x07q', '6n0774', '1w758v', 'y6jx7j', 'n0kjqn', '8p25wv', '2j05l
4', 'wzqvj6', 'p1ml9j', 'm8j10x', '1w75px', 'v0qln2', 'o0lyj4', 'm8jwqv', 'k0xr3
w', '4l162k', '0vm6mk', 'o0ly48', '9qj6y0', '8p29ln', '2j06q2', 'zzkpqm', 'p1mz2
q', 'n0kx6m', '9qj6qm', 'xz1nzw', 'wzqm0l', 'm8jw57', '7o07py', 'zzkpvl', 'm8jw7
p', '8p295q', '6n0664', '2j06mq', 'wzqm2o', 'j02qm4', '9qj6vx', '2j0614', 'o0ly2
j', '4l16km', 'r0o17o', 'k0xrqv', 'zzk7r3', 'v0q3v2', 'l2xq33', '7o0rw6', 'y6j7v
0', 'k0xpx9', '5mwpw0', '4l1owk', 'v0q3y4', 'l2xq8n', '4l1ovk', 'r0ozyn', '9qjw7
m', 'zzk72m', 'o0lw65', '4l1olj', 'v0q30l', '9qjw4m', 'o0lwny', '4l1o8x', 'p1mx5
x', '7o0rpy', 'v0q3z6', '8p2vm3', 'wzq7pl', 'j029y8', '1w7l8v', 'r0ozzm', 'j0299
y', '6n0qr4', 'zzk79w', 'o0lwzj', '5mwp4j', 'v0q3k7', '4l1okm', 'p1mx3j', '2j0mr
4', 'r0oxmo', 'k0xnov', 'zzkjl3', 'o0lro4', '5mwqkq', 'r0oxwy', '8p2wxo', 'xz131
z', 'j02mwn', 'q3zw73', '6n0rx9', 'xz13xq', '8p2wln', '5mwqv0', 'q3zw83', 'm8jp4
8', 'l2xo66', 'm8jp88', 'j02m83', 'l2xo56', '9qjxrq', 'j02m78', '9qjx5q', '4l1p6
x', 'v0q13v', 'r0oxxm', 'p1mvv9', '4l1pn7', 'v0q16v', 'j02mry', 'y6w0mj', 'r0ox5
o', 'j02mx4', 'zzkj02', 'l2xovz', '1w7k2w', 'l2xjpz', 'y6jzqp', 'j024jn', '0vmjr
7', 'v0qw92', 'r0opoy', 'v0qw72', 'j024l2', 'o0lmv8', 'l2xjyn', 'l2xj4n', 'l2xj6
n', '5mwom9', '7o0q91', '4l1n8j', '1w7k1p', 'q3zorw', 'n0kl7j', 'p1mnlx', 'v0qwl
6', 'r0opxm', 'v0qwwv', 'zzk9mw', '5mwolm', '2j0lr4', '3k02q8', '2j01o4', '4l13j
m', '0vmzq7', '1w707x', '4l13wo', '2j01x5', '0vmzxk', '2j01ql', '2j01zl', '8p2jp
n', '1w70wp', '4l138j', '5mw4n9', '3k02zr', 'xz1kqw', '3k0269', '9qjkwq', 'j02rm
y', 'v0q66v', 'n0kyyl', 'y6jlyj', '0vm5p3', 'zzkol2', '2j0794', '6n0mw7', '4lnqk
k', '9qjp18', 'j02xzn', 'm8j0yv', 'l2xz4n', 'n0k168', 'n0k108', 'p1m9oq', 'o0l25
5', 'zzko4m', 'y6jnrz', 'o0l2ky', 'l2xz9m', 'k0xyp6', 'l2xzom', '7o0nqy', 'zzkom
w', 'q3z415', 'k0xyyr', 'j02xoy', '6n0294', 'zzk0l2', 'wzqro6', 'xz1wv8', 'v0qpq
7', 'l2xv13', '7o0416', '6n02xp', '0vmnx7', 'y6jyp0', 'p1m326', 'm83ywv', 'l2xv6
n', 'j02o02', '7o049j', 'r0o7qq', '7o048j', 'wzqr37', 'o0l1p5', 'l2xv76', 'l2xv0
6', 'j02oq3', '2j0rm0', 'wzqr7l', 'y6jyz1', 'y6jyl1', 'n0kzyl', 'o0l12z', 'q3z55
5', 'zzwrlw', 'm83m2x', 'j0wnj4', '6n19w7', '3k9q08', '3k9q98', 'r03mry', 'q37lv
v', 'k09o8w', 'n0wn2k', 'l21p6n', 'l21p2n', 'o049n8', 'n0wn58', 'l21pmn', 'k09o7
4', 'k09oz4', 'xz2pn3', 'wzw97l', '0v0pjr', '4lwr3x', '8p1ko3', '5m1r0m', '6n1l9
4', '3k9rry', '9q1o2n', 'y6wqvp', 'wzw1q6', '0v0439', '3k943y', '5m173m', '8p143
q', 'xz2r28', 'k09j1r', 'm83l6p', 'q37p65', '0v0o67', 'wzw0zo', '2jw4jq', '4lw4l
7', '6n14n4', '9q14qn', 'k09j0r', 'r03lro', 'n0wm0l', 'p1wo19', 'q37p35', 'j0wvz
n', 'r03qqm', 'v07xxv', 'k09w8w', 'wzw00o', '8p10zo', '7o1jy6', '7o1j36', '0v02v
k', 'xz200v', 'y6w00j', 'zzw66w', 'y6wq0x', 'p1wr56', '0v0449', '1wz44v', '2jw44
q', 'p1wrq6', 'k09w79', '3k944y', '4lwq5j', '2jwo62', '4lw447', 'xz2rn3', 'l21lq
6', '5m12q9', 'r03lxp', '7o1jqy', '2jwo10', 'xz2rkw', 'n0w31j', 'j0wvo8', 'y6wk1
j', 'v075vv', 'n0wr3l', '3k977y', 'v0759v', '6n1vw4', 'p1wjmj', '3k9708', 'r03j3
o', '5m1k1j', 'v075y7', 'k09kmv', '6n1vj7', 'xz2joz', 'l21343', '4lwj9o', 'p1wj6
4', '9q1238', '2jw9j5', 'm83qlz', '4lwj4k', 'xz2j5q', 'k09kl9', '7o1wlj', '2jw9y
l', 'n0wrjm', '5m1k69', 'xz2jn3', 'n0wrvm', 'zzw1jm', 'n0wrlj', '3k9729', 'v0756
6', 'l213zm', '9q128q', 'm83vm7', '7o12j8', '1wzqrv', 'n0wprl', '7o1228', 'xz2v1
v', 'n0wpwn', '7o1217', '4lw2xm', 'xz2v88', 'xz2vo8', 'k0934w', '6n1wyp', '0v0q3
7', 'm83v8v', '4lw2lo', 'v079x2', '7o1296', 'm83v5z', 'k0k2jv', '3k7v88', 'v0584
7', 'o0ov5j', 'j0jz04', '7owk97', 'l2346q', '2j9zz0', '9q277q', 'k0k44r', '8pn73
q']
INFO root: Found anime: One Piece (Dub)
DEBUG root: Extracting stream info of id: k0xnov
DEBUG root: API call URL: https://9anime.is/ajax/episode/info with params {'id':
 'k0xnov', 'server': '33', 'ts': '1530270000', '_': 834}
DEBUG root: URL: https://www6.9anime.is/ajax/episode/info?id=k0xnov&server=33&ts
=1530270000&_=834
DEBUG root: Returned data: {'grabber': 'https://www6.9anime.is/grabber-api/?serv
er=33', 'params': [], 'backup': 0, 'target': 'https://www.rapidvideo.com/e/FRMLA
2O95F', 'type': 'iframe', 'name': '294', 'subtitle': ''}
DEBUG root: Calling Rapid url: https://www.rapidvideo.com/e/FRMLA2O95F&q=720p
https://www3487.playercdn.net/187/0/YQn5zTTuOU2yIBG0XNG4Nw/1530292640/180524/VxW
2ZojczTDDuPz.mp4

**Comment by vn-ki** [comment]
@nirmankmr The other one too, please

**Comment by vn-ki** [comment]
Can you please try to download using the stream url, (which you got from `--url`)? Use idm or aria2. If it doesn't error, the problem is with the downloader of this tool.

**Comment by nirmankmr** [comment]
@vn-ki  Ok, i will try that from home.  Is Free Download Manager supported or idm is needed?

**Comment by vn-ki** [comment]
Anything should work. At least try it with your browser.

**Comment by nirmankmr** [comment]
@vn-ki  I think you are right. Using url and external downloader, got the download!
BTW, awesome tool you created. Kudos!!!

**Comment by vn-ki** [comment]
I'll close this issue as 9anime has been stable for the last 3 days.

@nirmankmr Thank you. Also the latest version can use external downloaders. This would increase your speed and the files will be named properly (`SteinsGate/SteinsGate_1`, for example). Use `-xd {aria2}` to use it. Of course you need to have aria2 installed.
